name: octopus_extensions
description: A collection of Dart extensions and helpers that enhance core types like List, Map, String, and DateTime with concise, reusable functionality.
version: 2.2.28

homepage: https://github.com/octopusllc/extensions

environment:
  sdk: ^3.6.2

dependencies:
  # -> Tools
  intl: ^0.20.2

dev_dependencies:
  flutter_lints: ^5.0.0